### ISSUE TITLE
Hyperlinks 

### ISSUE THREAD

**Issue by CLTWorkshop** [CLTWorkshop/CLTWorkshop.github.io#5]
-website link for the 4th CLTW goes to LREC website, it should go to the Bangor site (I added the wrong href)
-website link for the 3rd CLTW doesn't work, we can remove
-Add in underline on link text (See here) for link to CLTW roundtable discussion (Background Section)

**Comment by aagroome** [comment]
- What's the url to the correct site?
- I can't find any urls that don't work. Which is this?
- The words "See here" are underlined and link to this page: https://techiaith.bangor.ac.uk/a-roundtable-discussion-to-promote-a-strategic-vision-for-celtic-language-technologies/?lang=en Is this correct?

**Comment by CLTWorkshop** [comment]
* I've added the correct url in the content document
* It seems to be working now! I guess it must have been a problem on my end?
* That section was recommended to be removed, so it's ok

**Comment by CLTWorkshop** [comment]
The link for the submission to the Soft Conf page is not working!
